In [26]:
import xarray as xr
import numpy as np
import pandas as pd
import plotly.graph_objects as go

In [27]:
# Open 

f = 'data/NO_TS_TG_KielHoltenauTG.nc'
ds = xr.open_dataset(f)
df = ds.to_dataframe().reset_index()

In [28]:
ds

<xarray.Dataset> Size: 17MB
Dimensions:    (TIME: 1018869, DEPTH: 1)
Coordinates:
  * TIME       (TIME) datetime64[ns] 8MB 2014-01-19T06:00:00 ... 2025-02-28T2...
    DEPH       (DEPTH) float32 4B 0.0
    LATITUDE   float32 4B 54.38
    LONGITUDE  float32 4B 10.2
    STATION    |S64 64B b'KielHoltenauTG'
Dimensions without coordinates: DEPTH
Data variables:
    TIME_QC    (TIME) int8 1MB 1 1 1 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 1 1 1 1 1
    SLEV       (TIME, DEPTH) float32 4MB 0.52 0.52 0.53 ... -0.027 -0.027 -0.017
    SLEV_QC    (TIME, DEPTH) float32 4MB 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0
Attributes: (12/42)
    data_mode:                      R
    id:                             NO_TS_TG_KielHoltenauTG
    institution:                    Waterways and Shipping Authority Luebeck
    institution_country:            Germany
    institution_edmo_code:          2313
    naming_authority:               Copernicus Marine In Situ
    ...                             ...
    update_interval:                P1M
    date_modified:                  2025-03-03T07:42:30Z
    date_created:                   2025-03-03T07:42:30Z
    history:                        2025-03-03T07:42:30Z : Creation
    last_date_observation:          2025-02-28T23:50:00Z
    bottom_depth:

In [29]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1018869 entries, 0 to 1018868
Data columns (total 9 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   TIME       1018869 non-null  datetime64[ns]
 1   DEPTH      1018869 non-null  int64
 2   TIME_QC    1018869 non-null  int8
 3   DEPH       1018869 non-null  float32
 4   LATITUDE   1018869 non-null  float32
 5   LONGITUDE  1018869 non-null  float32
 6   STATION    1018869 non-null  object
 7   SLEV       1018869 non-null  float32
 8   SLEV_QC    1018869 non-null  float32
dtypes: datetime64[ns](1), float32(5), int64(1), int8(1), object(1)
memory usage: 43.7+ MB

,TIME,DEPTH,TIME_QC,DEPH,LATITUDE,LONGITUDE,STATION,SLEV,SLEV_QC
0,2014-01-19 06:00:00.000000000,0,1,0.0,54.382999,10.204,b'KielHoltenauTG',0.52,1.0
1,2014-01-19 06:10:00.000000000,0,1,0.0,54.382999,10.204,b'KielHoltenauTG',0.52,1.0
2,2014-01-19 06:20:00.000000256,0,1,0.0,54.382999,10.204,b'KielHoltenauTG',0.53,1.0
3,2014-01-19 06:30:00.000000000,0,1,0.0,54.382999,10.204,b'KielHoltenauTG',0.53,1.0
4,2014-01-19 06:40:00.000000000,0,1,0.0,54.382999,10.204,b'KielHoltenauTG',0.53,1.0

In [30]:
# Just take quality check 1 data
print(df['SLEV_QC'].unique())

df_qc = df[df['SLEV_QC'] == 1]
df_qc.info()

[1. 3. 4.]
<class 'pandas.core.frame.DataFrame'>
Index: 902896 entries, 0 to 1018868
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   TIME       902896 non-null  datetime64[ns]
 1   DEPTH      902896 non-null  int64
 2   TIME_QC    902896 non-null  int8
 3   DEPH       902896 non-null  float32
 4   LATITUDE   902896 non-null  float32
 5   LONGITUDE  902896 non-null  float32
 6   STATION    902896 non-null  object
 7   SLEV       902896 non-null  float32
 8   SLEV_QC    902896 non-null  float32
dtypes: datetime64[ns](1), float32(5), int64(1), int8(1), object(1)
memory usage: 45.6+ MB

In [31]:
# Group the Data hurly and take the mean
df_hourly = df_qc.copy()
df_hourly.set_index('TIME', inplace=True)
display(df_hourly.head())

df_hourly = df_hourly.resample('h').mean(numeric_only=True)
df_hourly.reset_index(inplace=True)
df_hourly.info()
df_hourly.head()

,DEPTH,TIME_QC,DEPH,LATITUDE,LONGITUDE,STATION,SLEV,SLEV_QC
TIME,,,,,,,,
2014-01-19 06:00:00.000000000,0,1,0.0,54.382999,10.204,b'KielHoltenauTG',0.52,1.0
2014-01-19 06:10:00.000000000,0,1,0.0,54.382999,10.204,b'KielHoltenauTG',0.52,1.0
2014-01-19 06:20:00.000000256,0,1,0.0,54.382999,10.204,b'KielHoltenauTG',0.53,1.0
2014-01-19 06:30:00.000000000,0,1,0.0,54.382999,10.204,b'KielHoltenauTG',0.53,1.0
2014-01-19 06:40:00.000000000,0,1,0.0,54.382999,10.204,b'KielHoltenauTG',0.53,1.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97410 entries, 0 to 97409
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TIME       97410 non-null  datetime64[ns]
 1   DEPTH      95909 non-null  float64
 2   TIME_QC    95909 non-null  float64
 3   DEPH       95909 non-null  float32
 4   LATITUDE   95909 non-null  float32
 5   LONGITUDE  95909 non-null  float32
 6   SLEV       95909 non-null  float32
 7   SLEV_QC    95909 non-null  float32
dtypes: datetime64[ns](1), float32(5), float64(2)
memory usage: 4.1 MB

,TIME,DEPTH,TIME_QC,DEPH,LATITUDE,LONGITUDE,SLEV,SLEV_QC
0,2014-01-19 06:00:00,0.0,1.0,0.0,54.382999,10.204,0.526667,1.0
1,2014-01-19 07:00:00,0.0,1.0,0.0,54.382999,10.204,0.550000,1.0
2,2014-01-19 08:00:00,0.0,1.0,0.0,54.382999,10.204,0.576667,1.0
3,2014-01-19 09:00:00,0.0,1.0,0.0,54.382999,10.204,0.616667,1.0
4,2014-01-19 10:00:00,0.0,1.0,0.0,54.382999,10.204,0.647667,1.0

In [34]:
# Just take the data from 2023-01-01 
df_hourly = df_hourly[df_hourly['TIME'] > '2023-01-01']
df_hourly.sort_values('TIME', inplace=True)
df_hourly.reset_index(inplace=True, drop=True)
df_hourly.info()
df_hourly.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18959 entries, 0 to 18958
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TIME       18959 non-null  datetime64[ns]
 1   DEPTH      18955 non-null  float64
 2   TIME_QC    18955 non-null  float64
 3   DEPH       18955 non-null  float32
 4   LATITUDE   18955 non-null  float32
 5   LONGITUDE  18955 non-null  float32
 6   SLEV       18955 non-null  float32
 7   SLEV_QC    18955 non-null  float32
dtypes: datetime64[ns](1), float32(5), float64(2)
memory usage: 814.8 KB

,TIME,DEPTH,TIME_QC,DEPH,LATITUDE,LONGITUDE,SLEV,SLEV_QC
0,2023-01-01 01:00:00,0.0,1.0,0.0,54.382999,10.204,0.019667,1.0
1,2023-01-01 02:00:00,0.0,1.0,0.0,54.382999,10.204,-0.035333,1.0
2,2023-01-01 03:00:00,0.0,1.0,0.0,54.382999,10.204,-0.118667,1.0
3,2023-01-01 04:00:00,0.0,1.0,0.0,54.382999,10.204,-0.163667,1.0
4,2023-01-01 05:00:00,0.0,1.0,0.0,54.382999,10.204,-0.100333,1.0

In [ ]:
# Save Target Data
station = df['STATION'].unique()[0]
filename = f'{station}_hourly'

df_hourly.to_json(f'data/{filename}.json', orient='records', lines=True, date_format='iso')

: